### ISSUE TITLE
delta to strike solvers missing a term

### ISSUE THREAD

**Issue by sovboss** [satrapade/multiasset#10]
These two functions seem to be missing (0.5*vol^2)*maturity term inside the exp():
_# delta to put strike  
D2CK<-function(delta,close,vol,maturity){ 
  close*exp(qnorm(1-delta,sd=vol*sqrt(maturity),lower.tail=TRUE)) 
}_ 

_# delta to call strike  
D2PK<-function(delta,close,vol,maturity){ 
  close*exp(qnorm(delta,sd=vol*sqrt(maturity),lower.tail=TRUE)) 
}_

**Comment by nassuphis** [comment]
let me check

**Comment by nassuphis** [comment]
```r
# call premium to strike
C2K<-function(K,C,F,v,t,n=3){
  for(i in 1:n){
    d1<-(log(F/K)+(0.5*v^2)*t)/(v*sqrt(t))
    d2<-d1-v*sqrt(t)
    Nd1<-pnorm(d1)
    Nd2<-pnorm(d2)
    K<-F*Nd1/Nd2-C/Nd2
  }
  K
}

# put premium to strike
P2K<-function(K,P,F,v,t,n=3){
  for(i in 1:n){
    d1<-(log(F/K)+(0.5*v^2)*t)/(v*sqrt(t))
    d2<-d1-v*sqrt(t)
    Nmd1<-pnorm(-d1)
    Nmd2<-pnorm(-d2)
    K<-F*Nmd1/Nmd2+P/Nmd2
  }
  K
}

# delta to put strike 
D2CK<-function(delta,close,vol,maturity){
  close*exp(qnorm(1-delta,sd=vol*sqrt(maturity),lower.tail=TRUE))
}

# delta to call strike 
D2PK<-function(delta,close,vol,maturity){
  close*exp(qnorm(delta,sd=vol*sqrt(maturity),lower.tail=TRUE))
}
````

**Comment by nassuphis** [comment]
Yes indeed.
for a vol of 0.1  and a maturity of 0.25 the difference is 

> 0.25*0.1*0.1/2
[1] 0.00125

as a pct of spot. this is for the construction of the fixed-strike vol surface.
good catch, i should have noticed.
this means that vols at the strike are interpolated differently, the pillars are shifted
by at most 1pct (usually much less)
so i would expect marginal impact, but yes, its a stupid error.

**Comment by nassuphis** [comment]
all good otherwise?
